#! /bin/sh
rm -f .error$$
ERROR=0
export PATH=/usr/local/bin:/usr/bin:/bin:/usr/games LANG=C
(make $@ 2>&1 || touch .error$$)| \
`sed -ne "s/^top_srcdir *= *//p" < Makefile`/extras/buildsystem/make.pl
test -f .error$$ && ERROR=1
rm -f .error$$
exit $ERROR
